version: "3.8"

services:
  zap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_feedback
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - zap-db
  zap-db:
    image: postgres:14
    container_name: zap_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_hash:/var/lib/postgresql/data
volumes:
  postgres_data_hash:
