version: "3.8"

services:
  zap-db:
    image: postgres:14
    container_name: zap_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_hash:/var/lib/postgresql/data
volumes:
  redis-data:
  postgres_data_hash:
